table _Measures
	lineageTag: 130bd8ab-a8d4-44ad-afef-47622b9a8889

	measure 'Total Sales' = SUM(Transactions[Sales])
		formatString: \$#,0.0;(\$#,0.0);\$#,0.0
		lineageTag: bdea6b58-988e-4fd6-8f5b-b812bc07660c

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'CM Sales' = ```
			VAR selected_month= SELECTEDVALUE('Date Table'[Month])
			          RETURN 
			          TOTALMTD(CALCULATE([Total Sales],'Date Table'[Month]=selected_month),'Date Table'[Date])
			```
		lineageTag: a1f3c649-5bc0-4768-9845-fbcff41e4a76

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'PM Sales' = CALCULATE([CM Sales], DATEADD('Date Table'[Date],-1,MONTH))
		lineageTag: b815858b-17e7-4619-886d-e3712b63acae

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MoM Growth & Diff Sales' = ```
			
			
			    VAR month_diff= [CM Sales]-[PM Sales]
			    VAR mom = month_diff/ [PM Sales]
			    VAR _sign= IF(month_diff>0 ,"+","")
			    VAR _sign_trend=IF(month_diff>0,"∆","∇")
			
			    RETURN _sign_trend & " " & _sign & FORMAT(mom,"#0.0%" & " | " & _sign & FORMAT(month_diff/1000,"0.0K")) & " " & "vs LM"
			```
		lineageTag: e7b6919f-04c8-4e97-b830-f10a5f72b0a9

	measure 'Total Orders' = DISTINCTCOUNT(Transactions[transaction_id])
		lineageTag: f2578754-7bde-4d8b-8e84-1ac337a69142

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'CM Orders' = ```
			VAR selected_month= SELECTEDVALUE('Date Table'[Month])
			          RETURN 
			          TOTALMTD(CALCULATE([Total Orders],'Date Table'[Month]=selected_month),'Date Table'[Date])
			```
		formatString: 0
		lineageTag: 99b5bb6f-37a4-4762-81fe-6d2589798c9d

	measure 'PM Orders' = CALCULATE([CM Orders], DATEADD('Date Table'[Date],-1,MONTH))
		formatString: 0
		lineageTag: 97362d0d-1c38-4efb-8319-8dd8749b74c1

	measure 'MoM Growth & Diff Orders' = ```
			
			
			    VAR month_diff= [CM Orders]-[PM Orders]
			    VAR mom = month_diff/ [PM Orders]
			    VAR _sign= IF(month_diff>0 ,"+","")
			    VAR _sign_trend=IF(month_diff>0,"∆","∇")
			
			    RETURN _sign_trend & " " & _sign & FORMAT(mom,"#0.0%" & " | " & _sign & FORMAT(month_diff/1000,"0.0K")) & " " & "vs LM"
			```
		lineageTag: 9a59a349-5e87-44c5-b517-047089d049bc

	measure 'Total Quantity Sold' = SUM(Transactions[transaction_qty])
		formatString: 0
		lineageTag: 2c4369ad-1c10-4f55-aa14-48a6da5021e6

	measure 'CM Quantity' = ```
			VAR selected_month= SELECTEDVALUE('Date Table'[Month])
			          RETURN 
			          TOTALMTD(CALCULATE([Total Quantity Sold],'Date Table'[Month]=selected_month),'Date Table'[Date])
			```
		formatString: 0
		lineageTag: c2517d90-3503-4fae-add7-20268b52d550

	measure 'PM Quantity' = CALCULATE([CM Quantity], DATEADD('Date Table'[Date],-1,MONTH))
		formatString: 0
		lineageTag: f60ad718-059b-4c3a-9f23-e873cb2ca177

	measure 'MoM Growth & Diff Quantity' = ```
			
			
			    VAR month_diff= [CM Quantity]-[PM Quantity]
			    VAR mom = month_diff/ [PM Quantity]
			    VAR _sign= IF(month_diff>0 ,"+","")
			    VAR _sign_trend=IF(month_diff>0,"∆","∇")
			
			    RETURN _sign_trend & " " & _sign & FORMAT(mom,"#0.0%" & " | " & _sign & FORMAT(month_diff/1000,"0.0K")) & " " & "vs LM"
			```
		lineageTag: b7fe7a61-a8b4-4f81-96a8-58239298a6f4

	measure message = "Hover on this visual to see details"
		lineageTag: ca125b42-17d7-42b1-a43e-aef67942e925

	measure Placeholder = 0
		formatString: 0
		lineageTag: fc536fdf-3b71-4806-8f94-0fce1f963b65

	measure 'Label for Store Location' = SELECTEDVALUE(Transactions[store_location]) & " | " & FORMAT([Total Sales]/1000, "$0.00K")
		lineageTag: 8a69ac7d-2251-4edb-9173-eeed4e14bfe2

	measure 'Daily Average Sales' = AVERAGEX(ALLSELECTED(Transactions[transaction_date]),[Total Sales])
		lineageTag: 8b0f1b91-f892-4682-9782-7bfb8c397565

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Colour Bars' = IF([Total Sales]>[Daily Average Sales] ,"Above","Below")
		lineageTag: e5b001cc-720e-4e4a-867d-8fffec60b053

	measure 'Label for Product Category' = SELECTEDVALUE(Transactions[product_category]) & " | " & FORMAT([Total Sales]/1000, "$0.00K")
		lineageTag: dec117a6-72bd-4656-a998-7d9900a77292

	measure 'New MoM Label' = ```
			
			
			    VAR month_diff= [CM Sales]-[PM Sales]
			    VAR mom = month_diff/ [PM Sales]
			    VAR _sign= IF(month_diff>0 ,"+","")
			    VAR _sign_trend=IF(month_diff>0,"∆","∇")
			
			    RETURN _sign_trend & " " & _sign & FORMAT(mom,"#0.0%")
			```
		lineageTag: 6cceee80-709d-4565-af61-81f9b75ba308

	measure 'Label for Product Type' = SELECTEDVALUE(Transactions[product_type]) & " | " & FORMAT([Total Sales]/1000, "$0.00K")
		lineageTag: b81cc661-7665-4f12-96a6-15fc26d8da45

	column Column
		formatString: 0
		lineageTag: ed5b0d0d-fb74-4236-abe4-fc59e2093dba
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Column]

		annotation SummarizationSetBy = Automatic

	partition _Measures = calculated
		mode: import
		source = Row("Column", BLANK())

	annotation PBI_Id = ba418773628d49048f55315e46a518f1

